### ISSUE TITLE
Date-Newest not sorting correctly in test. 

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#94] opened 2013-11-20 20:58 UTC
In test: I think changing the sort to Date-Newest is actually sorting with the oldest resource at the top of the results list, not the newest. I noticed this while testing Chrome on Android, but I confirmed it in Windows Chrome. Production is sorting correctly.

Ernesto thought it might be something you could help fix. Sarah Sweeney noticed this issue. 

Could you help us fix this before the December 10 release?

**Comment by nestochan** [comment] 2013-11-21 11:25
@bassettsj we were wondering if you could sleuth out what component does this sorting to help us determine
if it's exl configuration of script related tweak that's needed.

**Comment by nestochan** [comment] 2013-11-21 14:53
@winthropo @bassettsj @jasf OK : this looks like it's ready to close... 
a reconfirmation of the sort settings for date in the mapping tables
followed up by a 
Primo Home > Deploy All page, deploy the Search Engine Configuration
seems to have fixed this.

confirmed with @sarahjeansweeney that it indeed is working.
to test do so in a clean in-cognito window in chrome or similar feature in another.

will close this issue by COB 11/21/2013.

**Closed as completed** 2013-11-21 17:34 UTC
Labels: question, primo configuration, javascript
