### ISSUE TITLE
Sticky facets in new release - buggy?

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#343] opened 2017-08-14 18:15 UTC
I can get the sticky facets to work occasionally, but most of the time when I hover over a facet in active filters I'm not getting the padlock that brings up the sticky option.  Can anyone else confirm or deny?

(Marked this as low importance because the method of triggering this option is arcane enough that I suspect it will be a Power Users Only thing.)

Info from ExL's [August Highlights](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Highlights/027Primo_August_2017_Highlights#Sticky_Facets) pasted below.

Sticky Facets
This enhancements allows users to make active facets persistent for an entire session. To make a facet persistent, the user must hover the cursor over the facet in the Active filters section of the new UI and then click the facet's padlock 

To remove a facet's persistence, the user only needs to click the facet's padlock.  Users can also remove a sticky facet by deleting the facet or resetting all filters.

**Comment by winthropo** [comment] 2017-08-14 18:31
I can't reproduce this problem in Chrome. But I don't like how they implemented this feature at all.

**Comment by RPagani** [comment] 2017-08-17 00:38
Also got this to work in Chrome... but it's not the most intuitive feature. I don't know that as a user I would know to hover over the facet to lock it. Probably need to make a tutorial to 1. point it out and 2. clarify what it is

**Comment by jasf-** [comment] 2017-08-17 12:16
Fair enough, sounds like a PEBCAC issue on my part. 😉   Will close this.

**Comment by jasf-** [comment] 2017-08-23 13:47
Reopening to comment.

I'm not a fan of how this is behaving.  If you do use this arcane feature you can get stuck in a lovely cul-de-sac, like so:

-Sign in.  Do a search.  Apply your favorite sticky filter/s.
-Now go to the browse and search for something - title, author, doesn't matter.  You'll get (x) results.
-Click through one of those results.  You might get this message even though the system just told you that you got (x) results.

![stickyfilterpurgatory](https://user-images.githubusercontent.com/4661920/29619509-4a25ce6c-87e9-11e7-87fe-11edc8d83c47.png)


This is because your sticky filters are still sticky.  Note that on this screen there is no way to adjust or even see the filters.  You have to be clever enough to start a new search where you can see them and then clear them.

Another bit that I don't like about how this is implemented:

-Start a search from the box on the library home page.
-Even though you're still signed in, you will not see your sticky filters on the results page. *but*
-If you now run a new search within SOS, your sticky filters reappear.

I think I understand why this is happening this way, but to an end user I suspect it would just seem buggy.

**Comment by winthropo** [comment] 2017-08-23 14:00
I can't reproduce your first bit. I signed in. Searched for "crispr." Filtered Peer Reviewed. Locked it in. Went to browse and Title Searched "Harry Potter" and I got results. 

What am I doing wrong?

**Comment by jasf-** [comment] 2017-08-23 15:14
Probably depends on your choices.  Maybe there's a peer reviewed item titled "Harry Potter"?

It's still doing it for me.  Here's a vid.  http://www.screencast.com/t/EV6v4asSw

**Comment by winthropo** [comment] 2017-08-23 15:33
I get it now. I'll file a bug ticket with our friends at EXL. Thanks for the screencast. 

My prediction: EXL is not going to see this as a bug and they are going to tell us to file something in Idea Exchange.

**Comment by winthropo** [comment] 2018-09-05 15:30
EXL told me this will be fixed in the February 2018 release.

**Comment by winthropo** [comment] 2019-03-06 16:02
According to EXL this issue was resolved in the Primo February 2018 Release. Please reopen if that isn't the case.

**Closed as completed by winthropo** 2019-03-06 16:02 UTC
Labels: low importance, Aug2017Release
