### ISSUE TITLE
Question about widgets for the libguides

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#190] opened 2015-06-16 18:19 UTC
The search widget for the "everything" scope does not seem to be working.  Suggestions? 

See on this page, the first two widgets (the page is hidden so you have to be logged in)
http://subjectguides.lib.neu.edu/aecontent.php?pid=10479&sid=175582

**Comment by elizoller** [comment] 2015-06-16 18:54
The issue is because the form relies on two javascript functions searchPrimo() and searchPrimoEvent(event) that have been included on the page level. These functions specifically look for items by id in the page. An id is meant to be a unique identifier and not repeating. With two search boxes on the same page, it repeats the id and then the function basically breaks because it's returning more than one object by that id.
Easy fix - only put one search box per page. 
But if you want more than one search box per page, I can rewrite these functions to look for objects relative to the one that called the function.

**Comment by kmerguerian** [comment] 2015-06-16 18:56
OK, that's no problem.  But what about on this page?  
http://subjectguides.lib.neu.edu/business

It looks like there's only one search box (not including the guide search) but the SoS widget still doesn't seem to work.

**Comment by kmerguerian** [comment] 2015-06-16 19:05
This one is working
http://subjectguides.lib.neu.edu/content.php?pid=19703&sid=137586

**Comment by elizoller** [comment] 2015-06-16 19:19
When I look at the code on the business guide, it has a search_scope value of "(NEU)" instead of "everything_scope"
`<input name="search_scope" value="(NEU)" type="hidden">`

**Comment by elizoller** [comment] 2015-06-17 11:47
@kmerguerian Let me know if you have a need for multiple search boxes on one page, otherwise I think I can close this ticket?

**Closed as completed** 2015-06-22 20:02 UTC
